/** Cloudflare build plugin. Produces a Worker + DO entry point with SSE/webhook/sync modes. */
import * as path from 'node:path';
import type { BuildContext, BuildPlugin } from './types.ts';
import {
	readUserWranglerConfig,
	validateUserWranglerConfig,
	mergeFlueAdditions,
	stripNoisyWranglerDefaults,
	writeDeployRedirectIfMissing,
	detectSandboxBindings,
	assertSandboxPackageInstalled,
	computeFlueMigrations,
	type FlueAdditions,
} from './cloudflare-wrangler-merge.ts';

export class CloudflarePlugin implements BuildPlugin {
	name = 'cloudflare';
	// Skip Flue's esbuild pass: wrangler bundles the entry itself, both for
	// `wrangler dev` and `wrangler deploy`. Pre-bundling caused subtle
	// resolution conflicts with `nodejs_compat` (e.g. `tar` package using
	// bare `fs`/`zlib`/`assert` imports). Letting wrangler be the only
	// bundler in the chain eliminates that whole category of problem and
	// makes our dev/deploy paths identical.
	bundle = 'none' as const;
	entryFilename = '_entry.ts';

	/**
	 * Per-build cache of the user's wrangler config. Both `generateEntryPoint`
	 * and `additionalOutputs` need it (for sandbox detection + the merge), and
	 * a fresh `CloudflarePlugin` instance is constructed for each build (see
	 * `resolvePlugin` in build.ts), so the cache is implicitly scoped to a
	 * single build.
	 */
	private userConfigCache: Awaited<ReturnType<typeof readUserWranglerConfig>> | undefined;

	private async getUserConfig(outputDir: string) {
		if (!this.userConfigCache) {
			this.userConfigCache = await readUserWranglerConfig(outputDir);
		}
		return this.userConfigCache;
	}

	async generateEntryPoint(ctx: BuildContext): Promise<string> {
		const { agents, roles } = ctx;
		const rolesJson = JSON.stringify(roles);

		const webhookAgents = agents.filter((a) => a.triggers.webhook);

		// Generate import statements for all agent handlers
		const agentImports = agents
			.map((a) => {
				const varName = agentVarName(a.name);
				const filePath = a.filePath.replace(/\\/g, '/');
				return `import ${varName} from '${filePath}';`;
			})
			.join('\n');

		// Manifest for /agents endpoint
		const manifest = JSON.stringify(
			{
				agents: agents.map((a) => ({
					name: a.name,
					triggers: a.triggers,
				})),
			},
			null,
			2,
		);

		// Generate one DO class per webhook agent
		const agentClasses = webhookAgents
			.map((a) => {
				const className = agentClassName(a.name);
				const handlerVar = agentVarName(a.name);
				return `export class ${className} extends Agent {
  async onRequest(request) {
    return handleAgentRequest(request, this, ${JSON.stringify(a.name)}, ${handlerVar});
  }

  async onFiberRecovered(ctx) {
    if (ctx.name?.startsWith('flue:')) {
      return handleFlueFiberRecovered(ctx, this, ${JSON.stringify(a.name)});
    }
    if (typeof super.onFiberRecovered === 'function') {
      return super.onFiberRecovered(ctx);
    }
  }
}`;
			})
			.join('\n\n');

		// Inspect the user's wrangler config (if any) for `Sandbox`-named DO
		// bindings. For each, emit an aliased re-export from `@cloudflare/sandbox`
		// so the bundle surfaces the class at the top level under the user's
		// chosen class_name. See `detectSandboxBindings` for the convention.
		const { config: userConfig } = await this.getUserConfig(ctx.outputDir);
		const sandboxClassNames = detectSandboxBindings(userConfig);
		const sandboxReExports = sandboxClassNames
			.map((name) => `export { Sandbox as ${name} } from '@cloudflare/sandbox';`)
			.join('\n');

		return `
// Auto-generated by @flue/sdk build (cloudflare)
import { Agent, routeAgentRequest } from 'agents';
import { Bash, InMemoryFs } from 'just-bash';
import {
  createFlueContext,
  InMemorySessionStore,
  bashFactoryToSessionEnv,
  resolveModel,
} from '@flue/sdk/internal';
import { runWithCloudflareContext, cfSandboxToSessionEnv } from '@flue/sdk/cloudflare';

${agentImports}

// ─── Config ─────────────────────────────────────────────────────────────────

const roles = ${rolesJson};
const skills = {};
const systemPrompt = '';
const manifest = ${manifest};

// ─── Infrastructure ─────────────────────────────────────────────────────────

// No build-time model default. The user sets model at runtime via
// \`init({ model: "provider/model-id" })\` for an agent default, or via
// \`{ model: "provider/model-id" }\` on any individual prompt/skill/task call.
const model = undefined;

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

/**
 * 'local' sandbox is not available on Cloudflare Workers.
 */
async function createLocalEnv() {
  throw new Error(
    "[flue] 'local' sandbox is not supported on Cloudflare Workers. " +
    "Use the default empty sandbox, pass a BashFactory, " +
    "or pass a sandbox instance (from any SDK — e.g. @cloudflare/sandbox " +
    "or a Flue connector) to init({ sandbox })."
  );
}

/**
 * Detect and wrap external sandbox instances (e.g. from @cloudflare/sandbox's
 * getSandbox()). Returns SessionEnv if the value looks like a Durable Object
 * RPC stub, null otherwise.
 *
 * NOTE on detection: The value returned by \`getSandbox()\` is a workerd RPC
 * Proxy. None of the obvious detection strategies work:
 *
 *   - Structural duck-typing (\`'X' in stub\`, \`typeof stub.X === 'function'\`):
 *     the proxy lies positively for any property name, so any check returns
 *     \`true\` regardless of what's actually on the remote.
 *   - \`instanceof <UserSandboxClass>\` (e.g. \`Sandbox\` from
 *     \`@cloudflare/sandbox\`): the user's class only exists on the in-DO
 *     side; over RPC the caller gets a generic stub.
 *   - \`instanceof DurableObject\` (imported from \`cloudflare:workers\`): the
 *     stub's prototype chain has a class *named* \`DurableObject\`, but it's a
 *     workerd-internal class with a different identity than the importable
 *     one. \`instanceof\` checks identity, not name, so it returns \`false\`.
 *
 * The one signal that does work — verified by runtime probe — is the string
 * name of the prototype's constructor. Workerd's internal RPC stub class is
 * named \`DurableObject\`, and \`Object.getPrototypeOf(stub).constructor.name\`
 * returns that string. This is a heuristic (it relies on a workerd-internal
 * naming convention, not a contractual API), but it's empirically correct
 * today and will misroute only if a user passes some other DO stub to
 * \`init({ sandbox })\` — in which case \`cfSandboxToSessionEnv\` will fail
 * loudly on first method call.
 */
function resolveSandbox(sandbox) {
  if (
    sandbox &&
    typeof sandbox === 'object' &&
    Object.getPrototypeOf(sandbox)?.constructor?.name === 'DurableObject'
  ) {
    return cfSandboxToSessionEnv(sandbox);
  }
  return null;
}

// Fallback in-memory store (used if no DO storage is available).
const memoryStore = new InMemorySessionStore();

// Create a DO-backed session store from the Durable Object's SQL storage.
function createDOStore(sql) {
  // Ensure the table exists
  sql.exec(
    'CREATE TABLE IF NOT EXISTS flue_sessions (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at INTEGER NOT NULL)'
  );
  return {
    async save(id, data) {
      const json = JSON.stringify(data);
      sql.exec(
        'INSERT OR REPLACE INTO flue_sessions (id, data, updated_at) VALUES (?, ?, ?)',
        id, json, Date.now()
      );
    },
    async load(id) {
      const rows = sql.exec('SELECT data FROM flue_sessions WHERE id = ?', id).toArray();
      if (rows.length === 0) return null;
      return JSON.parse(rows[0].data);
    },
    async delete(id) {
      sql.exec('DELETE FROM flue_sessions WHERE id = ?', id);
    },
  };
}

function createContextForRequest(id, payload, doInstance) {
  // Use DO SQLite storage by default, fall back to in-memory
  const defaultStore = doInstance?.ctx?.storage?.sql
    ? createDOStore(doInstance.ctx.storage.sql)
    : memoryStore;

  return createFlueContext({
    id,
    payload,
    env: doInstance?.env ?? {},
    agentConfig: {
      systemPrompt, skills, roles, model, resolveModel,
    },
    createDefaultEnv,
    createLocalEnv,
    defaultStore,
    resolveSandbox,
  });
}

function runWithInstanceContext(doInstance, fn) {
  return runWithCloudflareContext(
    { env: doInstance.env, agentInstance: doInstance, storage: doInstance.ctx.storage },
    fn,
  );
}

function assertAgentsDurabilityApi(doInstance, method) {
  if (typeof doInstance[method] !== 'function') {
		throw new Error(
			'[flue] The installed "agents" package does not provide the required Cloudflare Agents SDK method "' +
				method +
				'". Install or upgrade the "agents" package in your project.',
		);
	}
}

function runHandlerWithKeepAlive(doInstance, ctx, handler) {
  return runWithInstanceContext(doInstance, () => {
    assertAgentsDurabilityApi(doInstance, 'keepAliveWhile');
    return doInstance.keepAliveWhile(() => handler(ctx));
  });
}

function startWebhookFiber(doInstance, requestId, agentName, id, payload, handler) {
  const run = async (fiber) => {
    fiber?.stash?.({
      version: 1,
      kind: 'webhook',
      agentName,
      id,
      requestId,
      phase: 'running',
      startedAt: Date.now(),
    });

    const ctx = createContextForRequest(id, payload, doInstance);
    return runWithInstanceContext(doInstance, async () => {
      try {
        return await handler(ctx);
      } finally {
        ctx.setEventCallback(undefined);
      }
    });
  };

  assertAgentsDurabilityApi(doInstance, 'runFiber');
  return doInstance.runFiber('flue:webhook:' + requestId, run);
}

async function handleFlueFiberRecovered(ctx, _doInstance, agentName) {
  if (!ctx.name || !ctx.name.startsWith('flue:')) return;
  console.warn('[flue] Cloudflare fiber interrupted:', agentName, ctx.name, ctx.snapshot ?? null);
}

// ─── Shared Request Handler ────────────────────────────────────────────────

async function handleAgentRequest(request, doInstance, agentName, handler) {
  // Agent id is the DO "room name" set by routeAgentRequest
  const id = doInstance.name;

  // Parse payload
  let payload;
  try {
    payload = await request.json();
  } catch {
    payload = {};
  }

  const accept = request.headers.get('accept') || '';
  const isWebhook = request.headers.get('x-webhook') === 'true';
  const isSSE = accept.includes('text/event-stream') && !isWebhook;

  try {
    // Fire-and-forget (webhook mode)
    if (isWebhook) {
      const requestId = crypto.randomUUID();
      startWebhookFiber(doInstance, requestId, agentName, id, payload, handler).then(
        (result) => {
          console.log('[flue] Webhook handler complete:', agentName,
            result !== undefined ? JSON.stringify(result) : '(no return)');
        },
        (err) => {
          console.error('[flue] Webhook handler error:', agentName, err);
        },
      );
      return new Response(JSON.stringify({ status: 'accepted', requestId }), {
        status: 202,
        headers: { 'content-type': 'application/json' },
      });
    }

    // SSE streaming mode
    if (isSSE) {
      const { readable, writable } = new TransformStream();
      const writer = writable.getWriter();
      const encoder = new TextEncoder();
      let eventId = 0;
      let isIdle = false;

      const writeSSE = async (data, event) => {
        const lines = [];
        if (event) lines.push('event: ' + event);
        lines.push('id: ' + eventId++);
        lines.push('data: ' + JSON.stringify(data));
        lines.push('', '');
        await writer.write(encoder.encode(lines.join('\\n')));
      };

      const ctx = createContextForRequest(id, payload, doInstance);
      ctx.setEventCallback((event) => {
        if (event.type === 'idle') isIdle = true;
        writeSSE(event, event.type).catch(() => {});
      });

      (async () => {
        try {
          const result = await runHandlerWithKeepAlive(doInstance, ctx, handler);
          if (!isIdle) {
            await writeSSE({ type: 'idle' }, 'idle');
          }
          await writeSSE(
            { type: 'result', data: result !== undefined ? result : null },
            'result',
          );
        } catch (err) {
          await writeSSE(
            { type: 'error', error: String(err) },
            'error',
          );
          if (!isIdle) {
            await writeSSE({ type: 'idle' }, 'idle');
          }
        } finally {
          ctx.setEventCallback(undefined);
          await writer.close();
        }
      })();

      return new Response(readable, {
        headers: {
          'content-type': 'text/event-stream',
          'cache-control': 'no-cache',
          'connection': 'keep-alive',
        },
      });
    }

    // Sync mode (default)
    const ctx = createContextForRequest(id, payload, doInstance);
    try {
      const result = await runHandlerWithKeepAlive(doInstance, ctx, handler);
      return new Response(
        JSON.stringify({ result: result !== undefined ? result : null }),
        { headers: { 'content-type': 'application/json' } },
      );
    } finally {
      ctx.setEventCallback(undefined);
    }
  } catch (err) {
    console.error('[flue] Agent error:', agentName, err);
    return new Response(
      JSON.stringify({ error: String(err) }),
      { status: 500, headers: { 'content-type': 'application/json' } },
    );
  }
}

// ─── Per-Agent Durable Object Classes ──────────────────────────────────────

${agentClasses}

// ─── User-declared Sandbox re-exports ──────────────────────────────────────
// One line per DO binding in the user's wrangler.jsonc whose class_name
// contains "Sandbox". Flue aliases the single \`Sandbox\` class shipped by
// \`@cloudflare/sandbox\` so each user-chosen class_name resolves at the
// bundle's top level. The binding + container image configuration is owned
// by the user's wrangler.jsonc.
${sandboxReExports}

// ─── Worker Fetch Handler ───────────────────────────────────────────────────

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    // Health check
    if (url.pathname === '/health') {
      return new Response(JSON.stringify({ status: 'ok' }), {
        headers: { 'content-type': 'application/json' },
      });
    }

    // Agent manifest
    if (url.pathname === '/agents' && request.method === 'GET') {
      return new Response(JSON.stringify(manifest), {
        headers: { 'content-type': 'application/json' },
      });
    }

    // Route to per-agent DOs via the Agents SDK
    // URL: /agents/<agent-name>/<id>
    const response = await routeAgentRequest(request, env);
    if (response) return response;

    return new Response('Not found', { status: 404 });
  },
};
`;
	}

	async additionalOutputs(ctx: BuildContext): Promise<Record<string, string>> {
		const outputs: Record<string, string> = {};
		const webhookAgents = ctx.agents.filter((a) => a.triggers.webhook);

		// Per-agent DO bindings: one per webhook agent. Flue no longer forces a
		// `Sandbox` binding, container entry, or Dockerfile — users who want
		// container sandboxes declare those themselves in their own
		// wrangler.jsonc (preserved via the merge below). Flue only automates
		// the `export { Sandbox as ... }` re-export in the bundle (see
		// generateEntryPoint).
		const flueBindings = webhookAgents.map((a) => ({
			class_name: agentClassName(a.name),
			name: agentClassName(a.name),
		}));
		const flueSqliteClasses = flueBindings.map((b) => b.class_name);

		// Read and validate the user's wrangler config (if any). User's file
		// lives at outputDir and is never modified; the composed output is
		// written to dist/wrangler.jsonc. Wrangler's reader normalizes
		// relative paths (e.g. containers[].image) to absolute paths against
		// the user's config dir, so the merged file stays correct after we
		// write it to dist/.
		const { config: userConfig, path: userConfigPath } = await this.getUserConfig(
			ctx.outputDir,
		);
		if (userConfigPath) {
			console.log(`[flue] Merging with user wrangler config: ${userConfigPath}`);
		}
		validateUserWranglerConfig(userConfig);

		// Compute the migrations Flue wants to add for net-new agent classes.
		// Cloudflare migration tags are immutable once deployed, so we emit
		// one tag per class — that lets every redeploy be a no-op for already
		// deployed classes and a single-tag append for the truly net-new ones.
		// Renames and deletes are the user's responsibility (manual entries
		// in their wrangler.jsonc); Flue never auto-emits destructive
		// migrations.
		const flueMigrations = computeFlueMigrations(flueSqliteClasses, userConfig.migrations);

		// Flue's contributions to the wrangler config. Everything else in the
		// user's wrangler.jsonc passes through untouched during merge.
		// Derive the default worker name from outputDir (typically the project
		// root) rather than workspaceDir, since workspaceDir may be ./.flue/
		// which would produce a useless ".flue" worker name.
		// `path.basename` rather than `split('/').pop()` so this works on
		// Windows too (native path separator there is `\`).
		const additions: FlueAdditions = {
			defaultName: path.basename(ctx.outputDir) || 'flue-agents',
			// `_entry.ts` is generated by `build()` and bundled by wrangler at
			// `wrangler dev` / `wrangler deploy` time. We don't pre-bundle.
			main: '_entry.ts',
			doBindings: flueBindings,
			migrations: flueMigrations,
		};

		// Detect user-declared Sandbox bindings and verify the @cloudflare/sandbox
		// package is available before esbuild tries to resolve it. Log each
		// binding we've auto-wired so users can see what Flue did on their behalf.
		const sandboxClassNames = detectSandboxBindings(userConfig);
		if (sandboxClassNames.length > 0) {
			assertSandboxPackageInstalled(sandboxClassNames, [ctx.outputDir, ctx.workspaceDir]);
			for (const className of sandboxClassNames) {
				console.log(
					`[flue] Detected Sandbox-named DO binding "${className}" — ` +
						`re-exporting from @cloudflare/sandbox.`,
				);
			}
		}

		const merged = mergeFlueAdditions(userConfig, additions);

		// Strip wrangler-normalizer defaults that cause spurious warnings when
		// wrangler re-parses the file (notably `unsafe: {}`). See the function
		// doc for the full rationale. Mutates `merged` in place.
		stripNoisyWranglerDefaults(merged);

		// Always include the wrangler JSON schema reference if absent so the
		// generated file gets editor validation if someone opens it directly.
		if (typeof merged.$schema !== 'string') {
			merged.$schema = 'https://workers.cloudflare.com/schema/wrangler.json';
		}

		outputs['wrangler.jsonc'] = JSON.stringify(merged, null, 2);

		// Flue no longer emits a Dockerfile. Users who use container sandboxes
		// provide their own Dockerfile at whatever path their wrangler.jsonc's
		// `containers[].image` points to.

		// Side effect: write the wrangler deploy-redirect file at
		// outputDir/.wrangler/deploy/config.json so `wrangler deploy` run from
		// outputDir automatically picks up our generated dist/wrangler.jsonc.
		// Only written if not already present, to respect user intent.
		// This lives outside dist/, so it's handled here rather than through
		// the additionalOutputs return value (which writes relative to dist/).
		writeDeployRedirectIfMissing(ctx.outputDir);

		return outputs;
	}
}

function agentVarName(name: string): string {
	return 'handler_' + name.replace(/[^a-zA-Z0-9]/g, '_');
}

/**
 * Convert agent name to a PascalCase DO class name.
 * "hello" → "Hello", "with-cloudflare" → "WithCloudflare"
 *
 * routeAgentRequest() converts binding names to kebab-case for URL matching,
 * so "WithCloudflare" → "with-cloudflare" → URL /agents/with-cloudflare/:id
 */
function agentClassName(name: string): string {
	return name
		.split(/[-_]/)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join('');
}

