/** Cloudflare build plugin. Produces a Worker + DO entry point with SSE/webhook/sync modes. */
import type { BuildContext, BuildPlugin } from './types.ts';

export class CloudflarePlugin implements BuildPlugin {
	name = 'cloudflare';

	generateEntryPoint(ctx: BuildContext): string {
		const { agents, roles } = ctx;
		const rolesJson = JSON.stringify(roles);

		const webhookAgents = agents.filter((a) => a.triggers.webhook);

		// Generate import statements for all agent handlers
		const agentImports = agents
			.map((a) => {
				const varName = agentVarName(a.name);
				const filePath = a.filePath.replace(/\\/g, '/');
				return `import ${varName} from '${filePath}';`;
			})
			.join('\n');

		// Manifest for /agents endpoint
		const manifest = JSON.stringify(
			{
				agents: agents.map((a) => ({
					name: a.name,
					triggers: a.triggers,
				})),
			},
			null,
			2,
		);

		// Generate one DO class per webhook agent
		const agentClasses = webhookAgents
			.map((a) => {
				const className = agentClassName(a.name);
				const handlerVar = agentVarName(a.name);
				return `export class ${className} extends Agent {
  async onRequest(request) {
    return handleAgentRequest(request, this, ${JSON.stringify(a.name)}, ${handlerVar});
  }
}`;
			})
			.join('\n\n');

		return `
// Auto-generated by @flue/sdk build (cloudflare)
import { Agent, routeAgentRequest } from 'agents';
import { Bash, InMemoryFs } from 'just-bash';
import { getModel } from '@mariozechner/pi-ai';
import { createFlueContext, InMemorySessionStore, bashToSessionEnv } from '@flue/sdk/internal';
import { setCloudflareContext, clearCloudflareContext, cfSandboxToSessionEnv } from '@flue/sdk/cloudflare';

${agentImports}

// ─── Config ─────────────────────────────────────────────────────────────────

const roles = ${rolesJson};
const skills = {};
const systemPrompt = '';
const manifest = ${manifest};

// ─── Infrastructure ─────────────────────────────────────────────────────────

// No build-time model default. The user sets model at runtime via
// \`init({ model: "provider/model-id" })\` for a session default, or via
// \`{ model: "provider/model-id" }\` on any individual prompt/skill/task call.
const model = undefined;

function resolveModel(modelString) {
  const slash = modelString.indexOf('/');
  if (slash === -1) {
    throw new Error(
      '[flue] Invalid model "' + modelString + '". ' +
      'Use the "provider/model-id" format (e.g. "anthropic/claude-haiku-4-5").'
    );
  }
  const provider = modelString.slice(0, slash);
  const modelId = modelString.slice(slash + 1);
  const resolved = getModel(provider, modelId);
  if (!resolved) {
    throw new Error(
      '[flue] Unknown model "' + modelString + '". ' +
      'Provider "' + provider + '" / model id "' + modelId + '" ' +
      'is not registered with @mariozechner/pi-ai.'
    );
  }
  return resolved;
}

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 */
async function createDefaultEnv() {
  const bash = new Bash({
    fs: new InMemoryFs(),
    network: { dangerouslyAllowFullInternetAccess: true },
  });
  return bashToSessionEnv(bash);
}

/**
 * 'local' sandbox is not available on Cloudflare Workers.
 */
async function createLocalEnv() {
  throw new Error(
    "[flue] 'local' sandbox is not supported on Cloudflare Workers. " +
    "Use the default empty sandbox, pass a custom Bash instance, " +
    "or use getSandbox() from @cloudflare/sandbox for container sandboxes."
  );
}

/**
 * Detect and wrap @cloudflare/sandbox instances (from getSandbox()).
 * Returns SessionEnv if the sandbox is a CF sandbox, null otherwise.
 */
function resolveSandbox(sandbox) {
  if (
    sandbox && typeof sandbox === 'object' &&
    typeof sandbox.exec === 'function' &&
    typeof sandbox.readFile === 'function' &&
    typeof sandbox.destroy === 'function' &&
    !('getCwd' in sandbox) && !('fs' in sandbox)
  ) {
    return cfSandboxToSessionEnv(sandbox);
  }
  return null;
}

// Fallback in-memory store (used if no DO storage is available).
const memoryStore = new InMemorySessionStore();

// Create a DO-backed session store from the Durable Object's SQL storage.
function createDOStore(sql) {
  // Ensure the table exists
  sql.exec(
    'CREATE TABLE IF NOT EXISTS flue_sessions (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at INTEGER NOT NULL)'
  );
  return {
    async save(id, data) {
      const json = JSON.stringify(data);
      sql.exec(
        'INSERT OR REPLACE INTO flue_sessions (id, data, updated_at) VALUES (?, ?, ?)',
        id, json, Date.now()
      );
    },
    async load(id) {
      const rows = sql.exec('SELECT data FROM flue_sessions WHERE id = ?', id).toArray();
      if (rows.length === 0) return null;
      return JSON.parse(rows[0].data);
    },
    async delete(id) {
      sql.exec('DELETE FROM flue_sessions WHERE id = ?', id);
    },
  };
}

function createContextForRequest(sessionId, payload, doInstance) {
  // Use DO SQLite storage by default, fall back to in-memory
  const defaultStore = doInstance?.ctx?.storage?.sql
    ? createDOStore(doInstance.ctx.storage.sql)
    : memoryStore;

  return createFlueContext({
    sessionId,
    payload,
    env: doInstance?.env ?? {},
    agentConfig: {
      systemPrompt, skills, roles, model, resolveModel,
    },
    createDefaultEnv,
    createLocalEnv,
    defaultStore,
    resolveSandbox,
  });
}

// ─── Shared Request Handler ────────────────────────────────────────────────

async function handleAgentRequest(request, doInstance, agentName, handler) {
  // Session ID is the DO "room name" set by routeAgentRequest
  const sessionId = doInstance.name;

  // Parse payload
  let payload;
  try {
    payload = await request.json();
  } catch {
    payload = {};
  }

  // Set up Cloudflare context for runtime primitives
  setCloudflareContext({ env: doInstance.env, agentInstance: doInstance, storage: doInstance.ctx.storage });

  const accept = request.headers.get('accept') || '';
  const isWebhook = request.headers.get('x-webhook') === 'true';
  const isSSE = accept.includes('text/event-stream') && !isWebhook;

  try {
    // Fire-and-forget (webhook mode)
    if (isWebhook) {
      const requestId = crypto.randomUUID();
      const ctx = createContextForRequest(sessionId, payload, doInstance);
      handler(ctx).then(
        (result) => {
          ctx.setEventCallback(undefined);
          clearCloudflareContext();
          console.log('[flue] Webhook handler complete:', agentName,
            result !== undefined ? JSON.stringify(result) : '(no return)');
        },
        (err) => {
          ctx.setEventCallback(undefined);
          clearCloudflareContext();
          console.error('[flue] Webhook handler error:', agentName, err);
        },
      );
      return new Response(JSON.stringify({ status: 'accepted', requestId }), {
        status: 202,
        headers: { 'content-type': 'application/json' },
      });
    }

    // SSE streaming mode
    if (isSSE) {
      const { readable, writable } = new TransformStream();
      const writer = writable.getWriter();
      const encoder = new TextEncoder();
      let eventId = 0;

      const writeSSE = async (data, event) => {
        const lines = [];
        if (event) lines.push('event: ' + event);
        lines.push('id: ' + eventId++);
        lines.push('data: ' + JSON.stringify(data));
        lines.push('', '');
        await writer.write(encoder.encode(lines.join('\\n')));
      };

      const ctx = createContextForRequest(sessionId, payload, doInstance);
      ctx.setEventCallback((event) => {
        writeSSE(event, event.type).catch(() => {});
      });

      (async () => {
        try {
          const result = await handler(ctx);
          await writeSSE(
            { type: 'result', data: result !== undefined ? result : null },
            'result',
          );
        } catch (err) {
          await writeSSE(
            { type: 'error', error: String(err) },
            'error',
          );
        } finally {
          ctx.setEventCallback(undefined);
          clearCloudflareContext();
          await writer.close();
        }
      })();

      return new Response(readable, {
        headers: {
          'content-type': 'text/event-stream',
          'cache-control': 'no-cache',
          'connection': 'keep-alive',
        },
      });
    }

    // Sync mode (default)
    const ctx = createContextForRequest(sessionId, payload, doInstance);
    const result = await handler(ctx);
    ctx.setEventCallback(undefined);
    clearCloudflareContext();
    return new Response(
      JSON.stringify({ result: result !== undefined ? result : null }),
      { headers: { 'content-type': 'application/json' } },
    );
  } catch (err) {
    clearCloudflareContext();
    console.error('[flue] Agent error:', agentName, err);
    return new Response(
      JSON.stringify({ error: String(err) }),
      { status: 500, headers: { 'content-type': 'application/json' } },
    );
  }
}

// ─── Per-Agent Durable Object Classes ──────────────────────────────────────

${agentClasses}

// Re-export Sandbox DO class for wrangler binding
export { Sandbox } from '@cloudflare/sandbox';

// ─── Worker Fetch Handler ───────────────────────────────────────────────────

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    // Health check
    if (url.pathname === '/health') {
      return new Response(JSON.stringify({ status: 'ok' }), {
        headers: { 'content-type': 'application/json' },
      });
    }

    // Agent manifest
    if (url.pathname === '/agents' && request.method === 'GET') {
      return new Response(JSON.stringify(manifest), {
        headers: { 'content-type': 'application/json' },
      });
    }

    // Route to per-agent DOs via the Agents SDK
    // URL: /agents/<agent-name>/<session-id>
    const response = await routeAgentRequest(request, env);
    if (response) return response;

    return new Response('Not found', { status: 404 });
  },
};
`;
	}

	esbuildOptions(_ctx: BuildContext): Record<string, any> {
		return {
			target: 'esnext',
			external: ['node:*', 'cloudflare:*'],
		};
	}

	additionalOutputs(ctx: BuildContext): Record<string, string> {
		const outputs: Record<string, string> = {};
		const webhookAgents = ctx.agents.filter((a) => a.triggers.webhook);

		// Per-agent DO bindings: one per webhook agent + Sandbox
		const agentBindings = webhookAgents.map((a) => ({
			class_name: agentClassName(a.name),
			name: agentClassName(a.name),
		}));
		const allBindings = [...agentBindings, { class_name: 'Sandbox', name: 'Sandbox' }];
		const allSqliteClasses = allBindings.map((b) => b.class_name);

		// Generate wrangler.jsonc
		const workerName = ctx.agentDir.split('/').pop() ?? 'flue-agents';
		outputs['wrangler.jsonc'] = JSON.stringify(
			{
				$schema: 'https://workers.cloudflare.com/schema/wrangler.json',
				name: workerName,
				main: 'server.mjs',
				compatibility_date: new Date().toISOString().split('T')[0],
				compatibility_flags: ['nodejs_compat'],
				containers: [
					{
						class_name: 'Sandbox',
						image: './Dockerfile',
					},
				],
				durable_objects: {
					bindings: allBindings,
				},
				migrations: [
					{
						new_sqlite_classes: allSqliteClasses,
						tag: 'v1',
					},
				],
			},
			null,
			2,
		);

		// Generate a basic Dockerfile for the sandbox container
		outputs['Dockerfile'] = [
			'FROM node:22-slim',
			'',
			'# Install common tools for agent sandboxes',
			'RUN apt-get update && apt-get install -y \\',
			'    git curl wget \\',
			'    python3 python3-pip \\',
			'    && rm -rf /var/lib/apt/lists/*',
			'',
			'WORKDIR /workspace',
			'',
			'# Keep container alive',
			'CMD ["sleep", "infinity"]',
			'',
		].join('\n');

		return outputs;
	}
}

function agentVarName(name: string): string {
	return 'handler_' + name.replace(/[^a-zA-Z0-9]/g, '_');
}

/**
 * Convert agent name to a PascalCase DO class name.
 * "hello" → "Hello", "with-cloudflare" → "WithCloudflare"
 *
 * routeAgentRequest() converts binding names to kebab-case for URL matching,
 * so "WithCloudflare" → "with-cloudflare" → URL /agents/with-cloudflare/:id
 */
function agentClassName(name: string): string {
	return name
		.split(/[-_]/)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join('');
}
