/** Cloudflare build plugin. Produces a Worker + DO entry point with SSE/webhook/sync modes. */
import type { BuildContext, BuildPlugin } from './types.ts';
import {
	readUserWranglerConfig,
	validateUserWranglerConfig,
	mergeFlueAdditions,
	writeDeployRedirectIfMissing,
	detectSandboxBindings,
	assertSandboxPackageInstalled,
	type FlueAdditions,
} from './cloudflare-wrangler-merge.ts';

export class CloudflarePlugin implements BuildPlugin {
	name = 'cloudflare';

	generateEntryPoint(ctx: BuildContext): string {
		const { agents, roles } = ctx;
		const rolesJson = JSON.stringify(roles);

		const webhookAgents = agents.filter((a) => a.triggers.webhook);

		// Generate import statements for all agent handlers
		const agentImports = agents
			.map((a) => {
				const varName = agentVarName(a.name);
				const filePath = a.filePath.replace(/\\/g, '/');
				return `import ${varName} from '${filePath}';`;
			})
			.join('\n');

		// Manifest for /agents endpoint
		const manifest = JSON.stringify(
			{
				agents: agents.map((a) => ({
					name: a.name,
					triggers: a.triggers,
				})),
			},
			null,
			2,
		);

		// Generate one DO class per webhook agent
		const agentClasses = webhookAgents
			.map((a) => {
				const className = agentClassName(a.name);
				const handlerVar = agentVarName(a.name);
				return `export class ${className} extends Agent {
  async onRequest(request) {
    return handleAgentRequest(request, this, ${JSON.stringify(a.name)}, ${handlerVar});
  }

  async onFiberRecovered(ctx) {
    if (ctx.name?.startsWith('flue:')) {
      return handleFlueFiberRecovered(ctx, this, ${JSON.stringify(a.name)});
    }
    if (typeof super.onFiberRecovered === 'function') {
      return super.onFiberRecovered(ctx);
    }
  }
}`;
			})
			.join('\n\n');

		// Inspect the user's wrangler config (if any) for `Sandbox`-named DO
		// bindings. For each, emit an aliased re-export from `@cloudflare/sandbox`
		// so the bundle surfaces the class at the top level under the user's
		// chosen class_name. See `detectSandboxBindings` for the convention.
		const { config: userConfig } = readUserWranglerConfig(ctx.outputDir);
		const sandboxClassNames = detectSandboxBindings(userConfig);
		const sandboxReExports = sandboxClassNames
			.map((name) => `export { Sandbox as ${name} } from '@cloudflare/sandbox';`)
			.join('\n');

		return `
// Auto-generated by @flue/sdk build (cloudflare)
import { Agent, routeAgentRequest } from 'agents';
import { Bash, InMemoryFs } from 'just-bash';
import { getModel } from '@mariozechner/pi-ai';
import { createFlueContext, InMemorySessionStore, bashFactoryToSessionEnv } from '@flue/sdk/internal';
import { runWithCloudflareContext, cfSandboxToSessionEnv } from '@flue/sdk/cloudflare';

${agentImports}

// ─── Config ─────────────────────────────────────────────────────────────────

const roles = ${rolesJson};
const skills = {};
const systemPrompt = '';
const manifest = ${manifest};

// ─── Infrastructure ─────────────────────────────────────────────────────────

// No build-time model default. The user sets model at runtime via
// \`init({ model: "provider/model-id" })\` for an agent default, or via
// \`{ model: "provider/model-id" }\` on any individual prompt/skill/task call.
const model = undefined;

function resolveModel(modelString) {
  const slash = modelString.indexOf('/');
  if (slash === -1) {
    throw new Error(
      '[flue] Invalid model "' + modelString + '". ' +
      'Use the "provider/model-id" format (e.g. "anthropic/claude-haiku-4-5").'
    );
  }
  const provider = modelString.slice(0, slash);
  const modelId = modelString.slice(slash + 1);
  const resolved = getModel(provider, modelId);
  if (!resolved) {
    throw new Error(
      '[flue] Unknown model "' + modelString + '". ' +
      'Provider "' + provider + '" / model id "' + modelId + '" ' +
      'is not registered with @mariozechner/pi-ai.'
    );
  }
  return resolved;
}

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

/**
 * 'local' sandbox is not available on Cloudflare Workers.
 */
async function createLocalEnv() {
  throw new Error(
    "[flue] 'local' sandbox is not supported on Cloudflare Workers. " +
    "Use the default empty sandbox, pass a BashFactory, " +
    "or pass a sandbox instance (from any SDK — e.g. @cloudflare/sandbox " +
    "or a Flue connector) to init({ sandbox })."
  );
}

/**
 * Detect and wrap external sandbox instances (e.g. from @cloudflare/sandbox's
 * getSandbox()). Returns SessionEnv if the object quacks like a container
 * sandbox, null otherwise.
 */
function resolveSandbox(sandbox) {
  if (
    sandbox && typeof sandbox === 'object' &&
    typeof sandbox.exec === 'function' &&
    typeof sandbox.readFile === 'function' &&
    typeof sandbox.destroy === 'function' &&
    !('getCwd' in sandbox) && !('fs' in sandbox)
  ) {
    return cfSandboxToSessionEnv(sandbox);
  }
  return null;
}

// Fallback in-memory store (used if no DO storage is available).
const memoryStore = new InMemorySessionStore();

// Create a DO-backed session store from the Durable Object's SQL storage.
function createDOStore(sql) {
  // Ensure the table exists
  sql.exec(
    'CREATE TABLE IF NOT EXISTS flue_sessions (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at INTEGER NOT NULL)'
  );
  return {
    async save(id, data) {
      const json = JSON.stringify(data);
      sql.exec(
        'INSERT OR REPLACE INTO flue_sessions (id, data, updated_at) VALUES (?, ?, ?)',
        id, json, Date.now()
      );
    },
    async load(id) {
      const rows = sql.exec('SELECT data FROM flue_sessions WHERE id = ?', id).toArray();
      if (rows.length === 0) return null;
      return JSON.parse(rows[0].data);
    },
    async delete(id) {
      sql.exec('DELETE FROM flue_sessions WHERE id = ?', id);
    },
  };
}

function createContextForRequest(id, payload, doInstance) {
  // Use DO SQLite storage by default, fall back to in-memory
  const defaultStore = doInstance?.ctx?.storage?.sql
    ? createDOStore(doInstance.ctx.storage.sql)
    : memoryStore;

  return createFlueContext({
    id,
    payload,
    env: doInstance?.env ?? {},
    agentConfig: {
      systemPrompt, skills, roles, model, resolveModel,
    },
    createDefaultEnv,
    createLocalEnv,
    defaultStore,
    resolveSandbox,
  });
}

function runWithInstanceContext(doInstance, fn) {
  return runWithCloudflareContext(
    { env: doInstance.env, agentInstance: doInstance, storage: doInstance.ctx.storage },
    fn,
  );
}

function runHandlerWithKeepAlive(doInstance, ctx, handler) {
  return runWithInstanceContext(doInstance, () => {
    if (typeof doInstance.keepAliveWhile === 'function') {
      return doInstance.keepAliveWhile(() => handler(ctx));
    }
    return handler(ctx);
  });
}

function startWebhookFiber(doInstance, requestId, agentName, id, payload, handler) {
  const run = async (fiber) => {
    fiber?.stash?.({
      version: 1,
      kind: 'webhook',
      agentName,
      id,
      requestId,
      phase: 'running',
      startedAt: Date.now(),
    });

    const ctx = createContextForRequest(id, payload, doInstance);
    return runWithInstanceContext(doInstance, async () => {
      try {
        return await handler(ctx);
      } finally {
        ctx.setEventCallback(undefined);
      }
    });
  };

  if (typeof doInstance.runFiber === 'function') {
    return doInstance.runFiber('flue:webhook:' + requestId, run);
  }

  return run(undefined);
}

async function handleFlueFiberRecovered(ctx, _doInstance, agentName) {
  if (!ctx.name || !ctx.name.startsWith('flue:')) return;
  console.warn('[flue] Cloudflare fiber interrupted:', agentName, ctx.name, ctx.snapshot ?? null);
}

// ─── Shared Request Handler ────────────────────────────────────────────────

async function handleAgentRequest(request, doInstance, agentName, handler) {
  // Agent id is the DO "room name" set by routeAgentRequest
  const id = doInstance.name;

  // Parse payload
  let payload;
  try {
    payload = await request.json();
  } catch {
    payload = {};
  }

  const accept = request.headers.get('accept') || '';
  const isWebhook = request.headers.get('x-webhook') === 'true';
  const isSSE = accept.includes('text/event-stream') && !isWebhook;

  try {
    // Fire-and-forget (webhook mode)
    if (isWebhook) {
      const requestId = crypto.randomUUID();
      startWebhookFiber(doInstance, requestId, agentName, id, payload, handler).then(
        (result) => {
          console.log('[flue] Webhook handler complete:', agentName,
            result !== undefined ? JSON.stringify(result) : '(no return)');
        },
        (err) => {
          console.error('[flue] Webhook handler error:', agentName, err);
        },
      );
      return new Response(JSON.stringify({ status: 'accepted', requestId }), {
        status: 202,
        headers: { 'content-type': 'application/json' },
      });
    }

    // SSE streaming mode
    if (isSSE) {
      const { readable, writable } = new TransformStream();
      const writer = writable.getWriter();
      const encoder = new TextEncoder();
      let eventId = 0;
      let isIdle = false;

      const writeSSE = async (data, event) => {
        const lines = [];
        if (event) lines.push('event: ' + event);
        lines.push('id: ' + eventId++);
        lines.push('data: ' + JSON.stringify(data));
        lines.push('', '');
        await writer.write(encoder.encode(lines.join('\\n')));
      };

      const ctx = createContextForRequest(id, payload, doInstance);
      ctx.setEventCallback((event) => {
        if (event.type === 'idle') isIdle = true;
        writeSSE(event, event.type).catch(() => {});
      });

      (async () => {
        try {
          const result = await runHandlerWithKeepAlive(doInstance, ctx, handler);
          if (!isIdle) {
            await writeSSE({ type: 'idle' }, 'idle');
          }
          await writeSSE(
            { type: 'result', data: result !== undefined ? result : null },
            'result',
          );
        } catch (err) {
          await writeSSE(
            { type: 'error', error: String(err) },
            'error',
          );
          if (!isIdle) {
            await writeSSE({ type: 'idle' }, 'idle');
          }
        } finally {
          ctx.setEventCallback(undefined);
          await writer.close();
        }
      })();

      return new Response(readable, {
        headers: {
          'content-type': 'text/event-stream',
          'cache-control': 'no-cache',
          'connection': 'keep-alive',
        },
      });
    }

    // Sync mode (default)
    const ctx = createContextForRequest(id, payload, doInstance);
    try {
      const result = await runHandlerWithKeepAlive(doInstance, ctx, handler);
      return new Response(
        JSON.stringify({ result: result !== undefined ? result : null }),
        { headers: { 'content-type': 'application/json' } },
      );
    } finally {
      ctx.setEventCallback(undefined);
    }
  } catch (err) {
    console.error('[flue] Agent error:', agentName, err);
    return new Response(
      JSON.stringify({ error: String(err) }),
      { status: 500, headers: { 'content-type': 'application/json' } },
    );
  }
}

// ─── Per-Agent Durable Object Classes ──────────────────────────────────────

${agentClasses}

// ─── User-declared Sandbox re-exports ──────────────────────────────────────
// One line per DO binding in the user's wrangler.jsonc whose class_name
// contains "Sandbox". Flue aliases the single \`Sandbox\` class shipped by
// \`@cloudflare/sandbox\` so each user-chosen class_name resolves at the
// bundle's top level. The binding + container image configuration is owned
// by the user's wrangler.jsonc.
${sandboxReExports}

// ─── Worker Fetch Handler ───────────────────────────────────────────────────

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    // Health check
    if (url.pathname === '/health') {
      return new Response(JSON.stringify({ status: 'ok' }), {
        headers: { 'content-type': 'application/json' },
      });
    }

    // Agent manifest
    if (url.pathname === '/agents' && request.method === 'GET') {
      return new Response(JSON.stringify(manifest), {
        headers: { 'content-type': 'application/json' },
      });
    }

    // Route to per-agent DOs via the Agents SDK
    // URL: /agents/<agent-name>/<id>
    const response = await routeAgentRequest(request, env);
    if (response) return response;

    return new Response('Not found', { status: 404 });
  },
};
`;
	}

	esbuildOptions(_ctx: BuildContext): Record<string, any> {
		return {
			target: 'esnext',
			// node:* and cloudflare:* are Workers runtime modules.
			// node-liblzma and @mongodb-js/zstd are just-bash optionalDependencies
			// wrapped in dynamic imports inside try/catch. Externalize so esbuild
			// doesn't try to resolve them; they wouldn't run in Workers anyway.
			external: ['node:*', 'cloudflare:*', 'node-liblzma', '@mongodb-js/zstd'],
		};
	}

	additionalOutputs(ctx: BuildContext): Record<string, string> {
		const outputs: Record<string, string> = {};
		const webhookAgents = ctx.agents.filter((a) => a.triggers.webhook);

		// Per-agent DO bindings: one per webhook agent. Flue no longer forces a
		// `Sandbox` binding, container entry, or Dockerfile — users who want
		// container sandboxes declare those themselves in their own
		// wrangler.jsonc (preserved via the merge below). Flue only automates
		// the `export { Sandbox as ... }` re-export in the bundle (see
		// generateEntryPoint).
		const flueBindings = webhookAgents.map((a) => ({
			class_name: agentClassName(a.name),
			name: agentClassName(a.name),
		}));
		const flueSqliteClasses = flueBindings.map((b) => b.class_name);

		// Flue's contributions to the wrangler config. Everything else in the
		// user's wrangler.jsonc passes through untouched during merge.
		// Derive the default worker name from outputDir (typically the project
		// root) rather than workspaceDir, since workspaceDir may be ./.flue/
		// which would produce a useless ".flue" worker name.
		const additions: FlueAdditions = {
			defaultName: ctx.outputDir.split('/').pop() ?? 'flue-agents',
			main: 'server.mjs',
			doBindings: flueBindings,
			migration: {
				tag: 'flue-v1',
				new_sqlite_classes: flueSqliteClasses,
			},
		};

		// Read and validate the user's wrangler config (if any), then merge
		// Flue's additions in. User's file lives at outputDir and is never
		// modified; the composed output is written to dist/wrangler.jsonc.
		const { config: userConfig, path: userConfigPath } = readUserWranglerConfig(ctx.outputDir);
		if (userConfigPath) {
			console.log(`[flue] Merging with user wrangler config: ${userConfigPath}`);
		}
		validateUserWranglerConfig(userConfig);

		// Detect user-declared Sandbox bindings and verify the @cloudflare/sandbox
		// package is available before esbuild tries to resolve it. Log each
		// binding we've auto-wired so users can see what Flue did on their behalf.
		const sandboxClassNames = detectSandboxBindings(userConfig);
		if (sandboxClassNames.length > 0) {
			assertSandboxPackageInstalled(sandboxClassNames, [ctx.outputDir, ctx.workspaceDir]);
			for (const className of sandboxClassNames) {
				console.log(
					`[flue] Detected Sandbox-named DO binding "${className}" — ` +
						`re-exporting from @cloudflare/sandbox.`,
				);
			}
		}

		const merged = mergeFlueAdditions(userConfig, additions);

		// Always include the wrangler JSON schema reference if absent so the
		// generated file gets editor validation if someone opens it directly.
		if (typeof merged.$schema !== 'string') {
			merged.$schema = 'https://workers.cloudflare.com/schema/wrangler.json';
		}

		outputs['wrangler.jsonc'] = JSON.stringify(merged, null, 2);

		// Flue no longer emits a Dockerfile. Users who use container sandboxes
		// provide their own Dockerfile at whatever path their wrangler.jsonc's
		// `containers[].image` points to.

		// Side effect: write the wrangler deploy-redirect file at
		// outputDir/.wrangler/deploy/config.json so `wrangler deploy` run from
		// outputDir automatically picks up our generated dist/wrangler.jsonc.
		// Only written if not already present, to respect user intent.
		// This lives outside dist/, so it's handled here rather than through
		// the additionalOutputs return value (which writes relative to dist/).
		writeDeployRedirectIfMissing(ctx.outputDir);

		return outputs;
	}
}

function agentVarName(name: string): string {
	return 'handler_' + name.replace(/[^a-zA-Z0-9]/g, '_');
}

/**
 * Convert agent name to a PascalCase DO class name.
 * "hello" → "Hello", "with-cloudflare" → "WithCloudflare"
 *
 * routeAgentRequest() converts binding names to kebab-case for URL matching,
 * so "WithCloudflare" → "with-cloudflare" → URL /agents/with-cloudflare/:id
 */
function agentClassName(name: string): string {
	return name
		.split(/[-_]/)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join('');
}
