/** Node.js build plugin. Produces a Hono HTTP server with SSE/webhook/sync modes. */
import type { BuildContext, BuildPlugin } from './types.ts';

export class NodePlugin implements BuildPlugin {
	name = 'node';

	generateEntryPoint(ctx: BuildContext): string {
		const { agents, roles, options, resolveSDKImport } = ctx;
		const modelProvider = options.model?.provider ?? 'anthropic';
		const modelId = options.model?.modelId ?? 'claude-haiku-4-5';
		const rolesJson = JSON.stringify(roles);

		const webhookAgents = agents.filter((a) => a.triggers.webhook);

		// Generate import statements for all agent handlers
		const agentImports = agents
			.map((a) => {
				const varName = agentVarName(a.name);
				const filePath = a.filePath.replace(/\\/g, '/');
				return `import ${varName} from '${filePath}';`;
			})
			.join('\n');

		// Build the handler map
		const handlerMapEntries = agents
			.map((a) => `  ${JSON.stringify(a.name)}: ${agentVarName(a.name)},`)
			.join('\n');

		// Build webhook agent names set
		const webhookNames = JSON.stringify(webhookAgents.map((a) => a.name));

		// Manifest for /agents endpoint
		const manifest = JSON.stringify(
			{
				agents: agents.map((a) => ({
					name: a.name,
					triggers: a.triggers,
				})),
			},
			null,
			2,
		);

		return `
// Auto-generated by @flue/sdk build (node)
import { Hono } from 'hono';
import { streamSSE } from 'hono/streaming';
import { serve } from '@hono/node-server';
import { Bash, InMemoryFs, MountableFs, ReadWriteFs } from 'just-bash';
import { getModel } from '@mariozechner/pi-ai';
import { createFlueContext } from '${resolveSDKImport('client')}';
import { InMemorySessionStore } from '${resolveSDKImport('session')}';
import { bashToSessionEnv } from '${resolveSDKImport('sandbox')}';
import { randomUUID } from 'node:crypto';

${agentImports}

// ─── Config ─────────────────────────────────────────────────────────────────

const skills = {};
const roles = ${rolesJson};
const systemPrompt = '';

const handlers = {
${handlerMapEntries}
};

const webhookAgents = new Set(${webhookNames});

const manifest = ${manifest};

// ─── Infrastructure ─────────────────────────────────────────────────────────

const model = getModel(${JSON.stringify(modelProvider)}, ${JSON.stringify(modelId)});

function resolveModel(modelString) {
  const slash = modelString.indexOf('/');
  if (slash !== -1) {
    return getModel(modelString.slice(0, slash), modelString.slice(slash + 1));
  }
  return getModel(${JSON.stringify(modelProvider)}, modelString);
}

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 * Uses InMemoryFs (no real filesystem access) with sensible defaults:
 * cwd = /home/user, /tmp exists, /bin and /usr/bin exist.
 */
async function createDefaultEnv() {
  const bash = new Bash({
    fs: new InMemoryFs(),
    network: { dangerouslyAllowFullInternetAccess: true },
  });
  return bashToSessionEnv(bash);
}

/**
 * Create a local sandbox backed by the host filesystem.
 * Mounts process.cwd() at /workspace via ReadWriteFs + MountableFs.
 */
async function createLocalEnv() {
  const rwfs = new ReadWriteFs({ root: process.cwd() });
  const fs = new MountableFs({ base: new InMemoryFs() });
  fs.mount('/workspace', rwfs);
  const bash = new Bash({
    fs,
    cwd: '/workspace',
    network: { dangerouslyAllowFullInternetAccess: true },
  });
  return bashToSessionEnv(bash);
}

// Default persistence store for Node — in-memory, process lifetime.
const defaultStore = new InMemorySessionStore();

function createContextForRequest(sessionId, payload) {
  return createFlueContext({
    sessionId,
    payload,
    env: process.env,
    agentConfig: {
      systemPrompt, skills, roles, model, resolveModel,
    },
    createDefaultEnv,
    createLocalEnv,
    defaultStore,
  });
}

// ─── Server ─────────────────────────────────────────────────────────────────

const app = new Hono();

app.get('/health', (c) => c.json({ status: 'ok' }));
app.get('/agents', (c) => c.json(manifest));

// Session ID is required in the URL
app.post('/agents/:name', (c) => {
  return c.json({
    error: 'Session ID is required. Use /agents/:name/:sessionId',
  }, 400);
});

app.post('/agents/:name/:sessionId', async (c) => {
  const name = c.req.param('name');
  const sessionId = c.req.param('sessionId');

  if (!handlers[name]) {
    return c.json({ error: 'Agent not found' }, 404);
  }
  if (!webhookAgents.has(name)) {
    return c.json({ error: 'Agent "' + name + '" is not web-accessible (no webhook trigger)' }, 404);
  }

  const handler = handlers[name];
  let payload;
  try {
    payload = await c.req.json();
  } catch {
    payload = {};
  }

  const accept = c.req.header('accept') || '';
  const isWebhook = c.req.header('x-webhook') === 'true';
  const isSSE = accept.includes('text/event-stream') && !isWebhook;

  // Fire-and-forget (webhook mode)
  if (isWebhook) {
    const requestId = randomUUID();
    const ctx = createContextForRequest(sessionId, payload);
    handler(ctx).then(
      (result) => {
        ctx.setEventCallback(undefined);
        console.log('[flue] Webhook handler complete:', name, result !== undefined ? JSON.stringify(result) : '(no return)');
      },
      (err) => {
        ctx.setEventCallback(undefined);
        console.error('[flue] Webhook handler error:', name, err);
      },
    );
    return c.json({ status: 'accepted', requestId }, 202);
  }

  // SSE streaming mode
  if (isSSE) {
    return streamSSE(c, async (stream) => {
      let eventId = 0;
      const ctx = createContextForRequest(sessionId, payload);
      ctx.setEventCallback((event) => {
        stream.writeSSE({ data: JSON.stringify(event), event: event.type, id: String(eventId++) }).catch(() => {});
      });

      try {
        const result = await handler(ctx);
        await stream.writeSSE({
          data: JSON.stringify({ type: 'result', data: result !== undefined ? result : null }),
          event: 'result',
          id: String(eventId++),
        });
      } catch (err) {
        await stream.writeSSE({
          data: JSON.stringify({ type: 'error', error: String(err) }),
          event: 'error',
          id: String(eventId++),
        });
      } finally {
        ctx.setEventCallback(undefined);
      }
    });
  }

  // Sync mode (default)
  try {
    const ctx = createContextForRequest(sessionId, payload);
    const result = await handler(ctx);
    ctx.setEventCallback(undefined);
    return c.json({ result: result !== undefined ? result : null });
  } catch (err) {
    console.error('[flue] Agent error:', name, err);
    return c.json({ error: String(err) }, 500);
  }
});

// ─── Start ──────────────────────────────────────────────────────────────────

const port = parseInt(process.env.PORT || '3000', 10);

const server = serve({ fetch: app.fetch, port });
console.log('[flue] Server listening on http://localhost:' + port);
console.log('[flue] Available agents: ' + ${JSON.stringify(webhookAgents.map((a) => a.name).join(', '))});

process.on('SIGINT', () => { server.close(); process.exit(0); });
process.on('SIGTERM', () => { server.close(); process.exit(0); });
`;
	}

	esbuildOptions(_ctx: BuildContext): Record<string, any> {
		return {
			platform: 'node',
			target: 'node22',
		};
	}
}

function agentVarName(name: string): string {
	return 'handler_' + name.replace(/[^a-zA-Z0-9]/g, '_');
}
