/** Node.js build plugin. Produces a Hono HTTP server with SSE/webhook/sync modes. */
import type { BuildContext, BuildPlugin } from './types.ts';

export class NodePlugin implements BuildPlugin {
	name = 'node';
	// Node has no platform-provided bundler — esbuild is our final-output
	// step here, producing a single self-contained `dist/server.mjs`.
	bundle = 'esbuild' as const;

	generateEntryPoint(ctx: BuildContext): string {
		const { agents, roles } = ctx;
		const rolesJson = JSON.stringify(roles);

		const webhookAgents = agents.filter((a) => a.triggers.webhook);

		// Generate import statements for all agent handlers. We register every
		// agent — including trigger-less ones — in the handler map so that the
		// CLI's `flue run` can invoke them in local mode. The webhookAgents
		// set below gates which are reachable over public HTTP when deployed.
		const agentImports = agents
			.map((a) => {
				const varName = agentVarName(a.name);
				const filePath = a.filePath.replace(/\\/g, '/');
				return `import ${varName} from '${filePath}';`;
			})
			.join('\n');

		// Build the handler map — includes ALL agents, not just webhook ones.
		const handlerMapEntries = agents
			.map((a) => `  ${JSON.stringify(a.name)}: ${agentVarName(a.name)},`)
			.join('\n');

		// Build webhook agent names set — used to gate the public HTTP route.
		const webhookNames = JSON.stringify(webhookAgents.map((a) => a.name));

		// Manifest for /agents endpoint
		const manifest = JSON.stringify(
			{
				agents: agents.map((a) => ({
					name: a.name,
					triggers: a.triggers,
				})),
			},
			null,
			2,
		);

		return `
// Auto-generated by @flue/sdk build (node)
import { Hono } from 'hono';
import { streamSSE } from 'hono/streaming';
import { serve } from '@hono/node-server';
import { Bash, InMemoryFs, MountableFs, ReadWriteFs } from 'just-bash';
import {
  createFlueContext,
  InMemorySessionStore,
  bashFactoryToSessionEnv,
  resolveModel,
  flueHttpError,
  methodNotAllowedError,
  readJsonRequestPayload,
} from '@flue/sdk/internal';
import { randomUUID } from 'node:crypto';

${agentImports}

// ─── Config ─────────────────────────────────────────────────────────────────

const skills = {};
const roles = ${rolesJson};
const systemPrompt = '';

const handlers = {
${handlerMapEntries}
};

const webhookAgents = new Set(${webhookNames});

// When the CLI starts this server via \`flue run\`, it sets FLUE_MODE=local.
// In local mode the HTTP route accepts any registered agent (including
// trigger-less CI-only agents). In any other mode the route is restricted to
// agents with \`webhook: true\`, preventing accidental public exposure of
// agents that the user only intended to invoke from their CI pipeline.
const isLocalMode = process.env.FLUE_MODE === 'local';

const manifest = ${manifest};

function jsonError(c, error) {
  for (const [name, value] of Object.entries(error.headers || {})) {
    c.header(name, value);
  }
  return c.json(error.body, error.status);
}

// ─── Infrastructure ─────────────────────────────────────────────────────────

// No build-time model default. The user sets model at runtime via
// \`init({ model: "provider/model-id" })\` for an agent default, or via
// \`{ model: "provider/model-id" }\` on any individual prompt/skill/task call.
const model = undefined;

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 * Uses InMemoryFs (no real filesystem access) with sensible defaults:
 * cwd = /home/user, /tmp exists, /bin and /usr/bin exist.
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

/**
 * Create a local sandbox backed by the host filesystem.
 * Mounts process.cwd() at /workspace via ReadWriteFs + MountableFs.
 */
async function createLocalEnv() {
  const rwfs = new ReadWriteFs({ root: process.cwd() });
  const fs = new MountableFs({ base: new InMemoryFs() });
  fs.mount('/workspace', rwfs);
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    cwd: '/workspace',
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

// Default persistence store for Node — in-memory, process lifetime.
const defaultStore = new InMemorySessionStore();

function createContextForRequest(id, payload) {
  return createFlueContext({
    id,
    payload,
    env: process.env,
    agentConfig: {
      systemPrompt, skills, roles, model, resolveModel,
    },
    createDefaultEnv,
    createLocalEnv,
    defaultStore,
  });
}

// ─── Server ─────────────────────────────────────────────────────────────────

const app = new Hono();

app.get('/health', (c) => c.json({ status: 'ok' }));
app.get('/agents', (c) => c.json(manifest));

// Agent id is required in the URL
app.all('/agents/:name', (c) => {
  if (c.req.method !== 'POST') {
    return jsonError(c, methodNotAllowedError('POST'));
  }
  return jsonError(c, flueHttpError(
    400,
    'missing_agent_id',
    'Agent id is required. Use /agents/:name/:id.',
    { agent: c.req.param('name') },
  ));
});

app.all('/agents/:name/:id', async (c) => {
  const name = c.req.param('name');
  const id = c.req.param('id');

  if (c.req.method !== 'POST') {
    return jsonError(c, methodNotAllowedError('POST'));
  }

  if (!handlers[name]) {
    return jsonError(c, flueHttpError(404, 'agent_not_found', 'Agent "' + name + '" was not found.', {
      agent: name,
    }));
  }
  if (!webhookAgents.has(name) && !isLocalMode) {
    return jsonError(c, flueHttpError(
      404,
      'agent_not_accessible',
      'Agent "' + name + '" is not web-accessible (no webhook trigger).',
      { agent: name },
    ));
  }

  const handler = handlers[name];
  const payloadResult = await readJsonRequestPayload(c.req.raw);
  if (!payloadResult.ok) {
    return jsonError(c, payloadResult.error);
  }
  const payload = payloadResult.payload;

  const accept = c.req.header('accept') || '';
  const isWebhook = c.req.header('x-webhook') === 'true';
  const isSSE = accept.includes('text/event-stream') && !isWebhook;

  // Fire-and-forget (webhook mode)
  if (isWebhook) {
    const requestId = randomUUID();
    const ctx = createContextForRequest(id, payload);
    handler(ctx).then(
      (result) => {
        ctx.setEventCallback(undefined);
        console.log('[flue] Webhook handler complete:', name, result !== undefined ? JSON.stringify(result) : '(no return)');
      },
      (err) => {
        ctx.setEventCallback(undefined);
        console.error('[flue] Webhook handler error:', name, err);
      },
    );
    return c.json({ status: 'accepted', requestId }, 202);
  }

  // SSE streaming mode
  if (isSSE) {
    return streamSSE(c, async (stream) => {
      let eventId = 0;
      let isIdle = false;
      const ctx = createContextForRequest(id, payload);
      ctx.setEventCallback((event) => {
        if (event.type === 'idle') isIdle = true;
        stream.writeSSE({ data: JSON.stringify(event), event: event.type, id: String(eventId++) }).catch(() => {});
      });

      try {
        const result = await handler(ctx);
        if (!isIdle) {
          const idle = { type: 'idle' };
          await stream.writeSSE({ data: JSON.stringify(idle), event: 'idle', id: String(eventId++) });
        }
        await stream.writeSSE({
          data: JSON.stringify({ type: 'result', data: result !== undefined ? result : null }),
          event: 'result',
          id: String(eventId++),
        });
      } catch (err) {
        await stream.writeSSE({
          data: JSON.stringify({ type: 'error', error: String(err) }),
          event: 'error',
          id: String(eventId++),
        });
        if (!isIdle) {
          const idle = { type: 'idle' };
          await stream.writeSSE({ data: JSON.stringify(idle), event: 'idle', id: String(eventId++) });
        }
      } finally {
        ctx.setEventCallback(undefined);
      }
    });
  }

  // Sync mode (default)
  try {
    const ctx = createContextForRequest(id, payload);
    const result = await handler(ctx);
    ctx.setEventCallback(undefined);
    return c.json({ result: result !== undefined ? result : null });
  } catch (err) {
    console.error('[flue] Agent error:', name, err);
    return jsonError(c, flueHttpError(500, 'agent_error', String(err), { agent: name }));
  }
});

app.notFound((c) => {
  return jsonError(c, flueHttpError(404, 'not_found', 'Not found.'));
});

// ─── Start ──────────────────────────────────────────────────────────────────

const port = parseInt(process.env.PORT || '3000', 10);

const server = serve({ fetch: app.fetch, port });
console.log('[flue] Server listening on http://localhost:' + port);
if (isLocalMode) {
  console.log('[flue] Mode: local (all agents invokable, including trigger-less)');
  console.log('[flue] Available agents: ' + ${JSON.stringify(agents.map((a) => a.name).join(', '))});
} else {
  console.log('[flue] Available agents: ' + ${JSON.stringify(webhookAgents.map((a) => a.name).join(', '))});
}

process.on('SIGINT', () => { server.close(); process.exit(0); });
process.on('SIGTERM', () => { server.close(); process.exit(0); });
`;
	}

	esbuildOptions(_ctx: BuildContext): Record<string, any> {
		return {
			platform: 'node',
			target: 'node22',
			// just-bash's archive code wraps these native addons in dynamic imports
			// inside try/catch and declares them as optionalDependencies. Externalize
			// so esbuild doesn't try to resolve them at bundle time — the failure
			// path is handled by just-bash at runtime with a clear error message.
			external: ['node-liblzma', '@mongodb-js/zstd'],
		};
	}
}

function agentVarName(name: string): string {
	return 'handler_' + name.replace(/[^a-zA-Z0-9]/g, '_');
}
