/** Node.js build plugin. Produces a Hono HTTP server with SSE/webhook/sync modes. */
import type { BuildContext, BuildPlugin } from './types.ts';

export class NodePlugin implements BuildPlugin {
	name = 'node';
	// Node has no platform-provided bundler — esbuild is our final-output
	// step here, producing a single self-contained `dist/server.mjs`.
	bundle = 'esbuild' as const;

	generateEntryPoint(ctx: BuildContext): string {
		const { agents, appEntry, workflows } = ctx;
		const runtimeVersion = JSON.stringify(ctx.runtimeVersion);

		const agentImports = agents
			.map((a, index) => {
				const varName = agentVarName(a.name, index);
				const filePath = a.filePath.replace(/\\/g, '/');
				return `import * as ${varName} from '${filePath}';`;
			})
			.join('\n');

		const workflowImports = workflows
			.map((workflow, index) => {
				const varName = workflowVarName(workflow.name, index);
				const filePath = workflow.filePath.replace(/\\/g, '/');
				return `import * as ${varName} from '${filePath}';`;
			})
			.join('\n');

		const agentModuleEntries = agents
			.map((a, index) => `  ${JSON.stringify(a.name)}: ${agentVarName(a.name, index)},`)
			.join('\n');
		const workflowModuleEntries = workflows
			.map((workflow, index) => `  ${JSON.stringify(workflow.name)}: ${workflowVarName(workflow.name, index)},`)
			.join('\n');

		// User-supplied app.ts (if any). The generated entry imports the user's
		// default export and dispatches all requests through `app.fetch`. When
		// no app.ts is present, the generated entry constructs a thin default
		// Hono that mounts `flue()` and renders canonical error envelopes.
		const userAppImport = appEntry ? `import userApp from '${appEntry.replace(/\\/g, '/')}';` : '';

		// All HTTP routing, SSE/webhook/sync mode handling, agent dispatch,
		// and error rendering live in @flue/runtime's runtime modules. The
		// generated entry's job is now narrow: import handlers, build the
		// runtime config, instantiate sandboxes, start the listener.
		return `
// Auto-generated by flue (target: node)
import { serve } from '@hono/node-server';
import { Bash, InMemoryFs } from 'just-bash';
import {
  createFlueContext,
  InMemorySessionStore,
  InMemoryRunStore,
  InMemoryRunRegistry,
  createRunSubscriberRegistry,
  bashFactoryToSessionEnv,
  resolveModel,
  configureFlueRuntime,
  createDefaultFlueApp,
  createDirectAgentHandler,
  createAgentDispatchProcessor,
  InMemoryDispatchQueue,
} from '@flue/runtime/internal';
${agentImports}
${workflowImports}
${userAppImport}

// ─── Config ─────────────────────────────────────────────────────────────────

const skills = {};
const systemPrompt = '';

function normalizeBuiltModules(agentModules, workflowModules) {
  const manifest = { agents: [], workflows: [] };
  const directHandlers = {};
  const receiveHandlers = {};
  const createdAgents = {};
  for (const [name, mod] of Object.entries(agentModules)) {
    if (!mod.default || mod.default.__flueCreatedAgent !== true || typeof mod.default.initialize !== 'function') throw new Error('[flue] Agent "' + name + '" must default-export createAgent(...).');
    const channels = normalizeChannelList(mod.channels, 'agent "' + name + '"');
    const hasExternalChannel = Object.keys(channels).some((channel) => channel !== 'http' && channel !== 'websocket');
    if (hasExternalChannel && typeof mod.receive !== 'function') {
      throw new Error('[flue] External-channel agent "' + name + '" must export async function receive(...).');
    }
    if (typeof mod.receive === 'function' && Object.keys(channels).length === 0) {
      throw new Error('[flue] Agent "' + name + '" exports receive(...) but no channels.');
    }
    manifest.agents.push({ name, channels, receive: typeof mod.receive === 'function', created: true });
    createdAgents[name] = mod.default;
    if (channels.http) directHandlers[name] = createDirectAgentHandler(mod.default);
    if (typeof mod.receive === 'function') receiveHandlers[name] = mod.receive;
  }

  for (const [name, mod] of Object.entries(workflowModules)) {
    if (typeof mod.run !== 'function') throw new Error('[flue] Workflow "' + name + '" must export async function run(...).');
    const channels = normalizeChannelList(mod.channels, 'workflow "' + name + '"');
    for (const channel of Object.keys(channels)) {
      if (channel !== 'http' && channel !== 'websocket') {
        throw new Error('[flue] Workflow "' + name + '" cannot subscribe to external channel "' + channel + '".');
      }
    }
    manifest.workflows.push({ name, channels });
    if (channels.http) workflowHandlers[name] = mod.run;
  }

  return { manifest, directHandlers, receiveHandlers, createdAgents, workflowHandlers };
}

function normalizeChannelList(value, label) {
  if (value === undefined) return {};
  if (!Array.isArray(value)) throw new Error('[flue] channels export for ' + label + ' must be an array.');
  const result = {};
  for (const entry of value) {
    const definition = normalizeChannelExport(entry, label + ' channel');
    result[definition.name] = true;
  }
  return result;
}

function normalizeChannelExport(value, label) {
  const definition = typeof value === 'function' ? value() : value;
  if (!definition || typeof definition !== 'object' || definition.__flueChannel !== true || typeof definition.name !== 'string' || definition.name.trim() === '') {
    throw new Error('[flue] Invalid ' + label + ': expected a channel definition or zero-argument channel factory.');
  }
  return definition;
}

const agentModules = {
${agentModuleEntries}
};
const workflowModules = {
${workflowModuleEntries}
};
const normalized = normalizeBuiltModules(agentModules, workflowModules);
const { manifest, directHandlers, receiveHandlers, createdAgents, workflowHandlers } = normalized;

// When the CLI starts this server via \`flue run\`, it sets FLUE_MODE=local.
const isLocalMode = process.env.FLUE_MODE === 'local';

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 * Uses InMemoryFs (no real filesystem access) with sensible defaults:
 * cwd = /home/user, /tmp exists, /bin and /usr/bin exist.
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

// Default persistence store for Node — in-memory, process lifetime.
const defaultStore = new InMemorySessionStore();
const runStore = new InMemoryRunStore();
const runRegistry = new InMemoryRunRegistry();
const runSubscribers = createRunSubscriberRegistry();
const dispatchQueue = new InMemoryDispatchQueue(createAgentDispatchProcessor({
  agents: createdAgents,
  createContext: createContextForRequest,
  runStore,
  runSubscribers,
  runRegistry,
}));

function createContextForRequest(id, runId, payload, req) {
  return createFlueContext({
    id,
    runId,
    payload,
    env: process.env,
    req,
    agentConfig: {
      systemPrompt, skills, model: undefined, resolveModel,
    },
    createDefaultEnv,
    defaultStore,
  });
}

// ─── Runtime seed ───────────────────────────────────────────────────────────

// Seed the public flue() sub-app with everything it needs to dispatch agent
// requests in-process. Must run before \`flue()\` handles any request — by
// virtue of being a top-level statement, it executes before \`serve(...)\`
// below binds the listener. User app.ts files that call \`flue()\` at top
// level are also fine because Hono routes are lazy: they read this config
// only when a request arrives.
configureFlueRuntime({
  target: 'node',
  runtimeVersion: ${runtimeVersion},
  manifest,
  handlers: directHandlers,
  receiveHandlers,
  dispatchQueue,
  workflowHandlers,
  createContext: createContextForRequest,
  runStore,
  runSubscribers,
  runRegistry,
});

// ─── App composition ────────────────────────────────────────────────────────

${
	appEntry
		? `// User-supplied app.ts: their default export owns the entire request
// pipeline. We just verify it exposes a fetch method and pass the
// listener through. flue() is available for them to mount, but the
// composition is theirs to author.
const app = userApp;
if (!app || typeof app.fetch !== 'function') {
  throw new Error(
    '[flue] app.ts default export must be a Hono app or an object with a fetch(request) method.'
  );
}`
		: `// No app.ts: build the default app via @flue/runtime so the generated entry
// stays \`hono\`-free (users only need hono in their node_modules when
// they author their own app.ts). The default mounts \`flue()\` at root
// and renders canonical Flue envelopes for unmatched paths.
const app = createDefaultFlueApp();`
}

// ─── Start ──────────────────────────────────────────────────────────────────

const port = parseInt(process.env.PORT || '3000', 10);

const server = serve({
  fetch: app.fetch,
  port,
  // SSE requests can outlive Node's default 300s request timeout.
  serverOptions: { requestTimeout: 0 },
});
console.log('[flue] Server listening on http://localhost:' + port);
if (isLocalMode) {
	console.log('[flue] Mode: local');
	console.log('[flue] Agents: ' + ${JSON.stringify(agents.map((a) => a.name).join(', '))});
} else {
	console.log('[flue] Agents: ' + ${JSON.stringify(agents.map((a) => a.name).join(', '))});
}

process.on('SIGINT', () => { server.close(); process.exit(0); });
process.on('SIGTERM', () => { server.close(); process.exit(0); });
`;
	}

	esbuildOptions(_ctx: BuildContext): Record<string, any> {
		return {
			platform: 'node',
			target: 'node22',
			// just-bash's archive code wraps these native addons in dynamic imports
			// inside try/catch and declares them as optionalDependencies. Externalize
			// so esbuild doesn't try to resolve them at bundle time — the failure
			// path is handled by just-bash at runtime with a clear error message.
			external: ['node-liblzma', '@mongodb-js/zstd'],
		};
	}
}

function agentVarName(name: string, index: number): string {
	const readableName = name.replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+|_+$/g, '') || 'agent';
	return `handler_${readableName}_${index}`;
}

function workflowVarName(name: string, index: number): string {
	const readableName = name.replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+|_+$/g, '') || 'workflow';
	return `workflow_${readableName}_${index}`;
}
