import type {
	AgentPromptImage,
	AgentPromptResponse,
	AttachedAgentEvent,
	FlueClient,
	FlueEvent,
	WorkflowRunResult,
} from '@flue/sdk';

export interface AgentRunInput {
	message: string;
	images?: AgentPromptImage[];
}

export interface AgentRunTarget {
	kind: 'agent';
	name: string;
	instanceId: string;
	input: AgentRunInput;
}

export interface WorkflowRunTarget {
	kind: 'workflow';
	name: string;
	input?: unknown;
}

export type RunTarget = AgentRunTarget | WorkflowRunTarget;

export type RunTargetResult =
	| { kind: 'agent'; instanceId: string; result: AgentPromptResponse }
	| { kind: 'workflow'; runId: string; result: unknown };

export async function runTarget(
	client: FlueClient,
	target: RunTarget,
	onEvent?: (event: AttachedAgentEvent | FlueEvent) => void | Promise<void>,
	signal?: AbortSignal,
): Promise<RunTargetResult> {
	if (target.kind === 'agent') {
		const admission = await client.agents.send(target.name, target.instanceId, {
			...target.input,
			signal,
		});
		const result = await client.agents.wait<AgentPromptResponse>(admission, { onEvent, signal });
		return { kind: 'agent', instanceId: target.instanceId, result };
	}
	const completed: WorkflowRunResult = await client.workflows.run(target.name, {
		input: target.input,
		onEvent,
		signal,
	});
	return { kind: 'workflow', runId: completed.runId, result: completed.result };
}

export function parseAgentInput(value: unknown): AgentRunInput {
	if (!isRecord(value) || typeof value.message !== 'string') {
		throw new TypeError('[flue] Agent input must be an object with a string "message" field.');
	}
	const keys = Object.keys(value);
	if (keys.some((key) => key !== 'message' && key !== 'images')) {
		throw new TypeError('[flue] Agent input accepts only "message" and optional "images" fields.');
	}
	if (value.images !== undefined && !isAgentImages(value.images)) {
		throw new TypeError(
			'[flue] Agent input "images" must be an array of { type: "image", data: string, mimeType: string } objects.',
		);
	}
	return value.images === undefined
		? { message: value.message }
		: { message: value.message, images: value.images };
}

export function assertRunIdAllowed(kind: RunTarget['kind'], id: string | undefined): void {
	if (kind === 'workflow' && id !== undefined) {
		throw new Error('[flue] --id is not supported for workflows. Workflow run IDs are generated by the runtime.');
	}
}

function isAgentImages(value: unknown): value is AgentPromptImage[] {
	return (
		Array.isArray(value) &&
		value.every(
			(image) =>
				isRecord(image) &&
				Object.keys(image).length === 3 &&
				image.type === 'image' &&
				typeof image.data === 'string' &&
				typeof image.mimeType === 'string',
		)
	);
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === 'object' && value !== null && !Array.isArray(value);
}
