/**
 * Generator for the Cloudflare Worker entry, served as the
 * `virtual:flue/worker` module (wrangler `main`, contributed by
 * `flueWorkerConfig()`). The sibling `@cloudflare/vite-plugin` resolves
 * `main` through Vite's plugin pipeline in both dev and build, so no file is
 * written to disk; bare imports (`agents`, `@flue/runtime/*`) in the
 * generated code resolve against the user's project root. The module is
 * generated per project rather than shipped as a bootstrap inside
 * `@flue/vite` because its content is project-specific: it imports the
 * user's `app.ts` (and optional `cloudflare.ts`) plus every scanned
 * `'use agent'` module. It is deliberately thin: all per-agent class
 * mechanics live in `createFlueAgentClass` / `createCloudflareAgentRuntime`
 * (real, tested code in `@flue/runtime`); the generated module only joins
 * the scanned `'use agent'` set to those factories.
 *
 * Ported from the CLI's legacy Cloudflare build plugin `generateEntryPoint`,
 * minus workflows, channels, the run registry, and the no-`app.ts` fallback —
 * on the new surface `app.ts` is required and the scan is the registration.
 */
import type { AgentScanResult } from './agent-scan.ts';

export interface GenerateCloudflareEntryOptions {
	/** Absolute path of the user's `app.*` entry (required on the new surface). */
	readonly appEntry: string;
	/** Absolute path of the user's `cloudflare.*` entry, if any. */
	readonly cloudflareEntry: string | undefined;
	/** The scanned `'use agent'` module set. */
	readonly agents: readonly AgentScanResult[];
	/**
	 * The configured provider IDs, or `undefined` for the all-built-ins
	 * default. The list is exhaustive: the `cloudflare` Workers AI binding
	 * provider is emitted only when the list is omitted or names it.
	 */
	readonly providers: readonly string[] | undefined;
}

/** Posix-normalize a path for embedding in generated import specifiers. */
function importPath(filePath: string): string {
	return JSON.stringify(filePath.replace(/\\/g, '/'));
}

export function generateCloudflareEntry(options: GenerateCloudflareEntryOptions): string {
	const { appEntry, cloudflareEntry, agents, providers } = options;
	const includeBindingProvider = providers === undefined || providers.includes('cloudflare');

	// One import per module file; one entry (and one DO class) per agent.
	const filePaths = [...new Set(agents.map((agent) => agent.filePath))];
	const varByPath = new Map(
		filePaths.map((filePath, index) => [filePath, `__flue_agent_module_${index}__`]),
	);
	const agentVar = (filePath: string) => varByPath.get(filePath) as string;
	const agentAccess = (agent: AgentScanResult) =>
		`${agentVar(agent.filePath)}[${JSON.stringify(agent.exportName)}]`;

	const agentImports = filePaths
		.map((filePath) => `import * as ${agentVar(filePath)} from ${importPath(filePath)};`)
		.join('\n');

	const scannedAgentEntries = agents
		.map(
			(agent) => `\t{ identity: ${JSON.stringify(agent.identity)}, agent: ${agentAccess(agent)} },`,
		)
		.join('\n');

	const agentIdentityEntries = agents
		.map(
			(agent) =>
				`\t${JSON.stringify(agent.identity)}: { bindingName: ${JSON.stringify(agent.bindingName)}, className: ${JSON.stringify(agent.className)} },`,
		)
		.join('\n');

	const agentClassExports = agents
		.map((agent) =>
			[
				`export const ${agent.className} = createFlueAgentClass({`,
				`\tAgentBase: Agent,`,
				`\truntime: cloudflareAgents,`,
				`\tclassName: ${JSON.stringify(agent.className)},`,
				`\tagentName: ${JSON.stringify(agent.identity)},`,
				// The `cloudflare` extension export is optional (per module — it
				// applies to every agent the module exports). Reflect.get keeps
				// identical semantics (undefined when absent) without the static
				// namespace member access bundlers flag as IMPORT_IS_UNDEFINED on
				// every agent module that does not declare the export.
				`\textension: Reflect.get(${agentVar(agent.filePath)}, 'cloudflare'),`,
				`});`,
			].join('\n'),
		)
		.join('\n\n');

	const userCloudflareImport = cloudflareEntry
		? `import * as userCloudflareModule from ${importPath(cloudflareEntry)};\nexport * from ${importPath(cloudflareEntry)};`
		: '';
	const userCloudflareValue = cloudflareEntry ? 'userCloudflareModule' : '{}';
	const reservedCloudflareExportNames = agents.map((agent) => agent.className);

	return `// Auto-generated by @flue/vite (target: cloudflare). Do not edit.
/* eslint-disable */
// @ts-nocheck
import { env } from 'cloudflare:workers';
import { Agent, getAgentByName } from 'agents';
import {
	configureFlueRuntime,
	createCloudflareAgentRuntime,
	createFlueContext,
	hasProvider,
	installDevLifecycleLogger,
	registerFlueAgents,
	resolveModel,
	setProvider,
} from '@flue/runtime/internal';
import {
	createCloudflareWorkerConfig,
	createFlueAgentClass,
	runWithCloudflareContext,
} from '@flue/runtime/cloudflare/internal';
${
	includeBindingProvider
		? "import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';"
		: ''
}
import userApp from ${importPath(appEntry)};
${userCloudflareImport}
${agentImports}
// The configured (or default) built-in provider set.
import 'virtual:flue/providers';
${
	includeBindingProvider
		? `
// ─── Workers AI binding provider ────────────────────────────────────────────
// User \`app.ts\` imports are hoisted above this body, so a user-supplied
// \`setProvider(...)\` with the \`cloudflare\` ID runs first; the guard below
// preserves it. The default routes through Cloudflare's default AI Gateway;
// pass \`gateway\` options (or \`false\`) to cloudflareBindingProvider to change
// that.

if (!hasProvider('cloudflare')) {
	setProvider(cloudflareBindingProvider({ binding: env.AI }));
}
`
		: ''
}

// ─── Registration ───────────────────────────────────────────────────────────
// The scan IS the registration: every 'use agent' agent joins the app.
// \`createAgentRouter()\` mounts in app.ts are pure routers over this set.

const registrations = [
${scannedAgentEntries}
];
registerFlueAgents(registrations);
const agents = registrations.map((registration) => ({
	name: registration.identity,
	agent: registration.agent,
}));
const agentIdentities = {
${agentIdentityEntries}
};

// ─── cloudflare.ts composition ──────────────────────────────────────────────

const userCloudflare = ${userCloudflareValue};
const reservedCloudflareExportNames = new Set(${JSON.stringify(reservedCloudflareExportNames)});
for (const name of Object.keys(userCloudflare)) {
	if (name === 'default') continue;
	if (reservedCloudflareExportNames.has(name)) {
		throw new Error('[flue] cloudflare.ts export "' + name + '" conflicts with a Flue-generated Worker export. Rename the authored export.');
	}
}
const cloudflareHandlers = 'default' in userCloudflare ? userCloudflare.default : {};
if (typeof cloudflareHandlers !== 'object' || cloudflareHandlers === null || Array.isArray(cloudflareHandlers)) {
	throw new Error('[flue] cloudflare.ts default export must be an object containing non-HTTP Worker handlers.');
}
if ('fetch' in cloudflareHandlers) {
	throw new Error('[flue] cloudflare.ts default export must not define fetch. Use app.ts for custom HTTP handling.');
}

// ─── Agent wiring ───────────────────────────────────────────────────────────
// There is no default sandbox: agents that want shell/filesystem tools
// declare an environment with useSandbox().

function createAgentContextForRequest({ instance, agentName, request, submissionId }) {
	return createFlueContext({
		id: instance.name,
		agentName,
		env: instance?.env ?? {},
		req: request,
		submissionId,
		agentConfig: { resolveModel },
	});
}

async function fetchAgent(binding, instanceId, request) {
	return (await getAgentByName(binding, instanceId)).fetch(request);
}

function runWithInstanceContext(doInstance, identity, fn) {
	return runWithCloudflareContext(
		{
			env: doInstance.env,
			storage: doInstance.ctx.storage,
			durableObjectIdentity: {
				bindingName: identity.bindingName,
				className: identity.className,
				name: doInstance.name,
				id: doInstance.ctx.id.toString(),
			},
		},
		fn,
	);
}

const devLifecycle = import.meta.env.DEV ? installDevLifecycleLogger() : undefined;
const cloudflareAgents = createCloudflareAgentRuntime({
	agents,
	createContext: createAgentContextForRequest,
	runWithInstanceContext: (instance, agentName, fn) => runWithInstanceContext(instance, agentIdentities[agentName], fn),
	onInteractionStart: devLifecycle?.onAgentInteractionStart,
});

// ─── Per-agent Durable Object classes ───────────────────────────────────────

${agentClassExports}

// ─── Runtime seed ───────────────────────────────────────────────────────────
// The worker-side seams (dispatch queue, DO request router, instance lookup)
// are built by tested runtime code; the entry injects the module-scope env
// and the \`agents\`-package fetch capability, which must stay out of the
// runtime's import graph.

configureFlueRuntime({
	target: 'cloudflare',
	devMode: import.meta.env.DEV,
	...createCloudflareWorkerConfig({ env, agentIdentities, fetchAgent }),
});

// ─── App composition ────────────────────────────────────────────────────────
// User-supplied app.ts. Its default export owns the entire request pipeline —
// the worker just verifies a fetch method exists and pipes through.

const flueApp = userApp;
if (!flueApp || typeof flueApp.fetch !== 'function') {
	throw new Error(
		'[flue] app.ts default export must be a Hono app or an object with a fetch(request, env, ctx) method.'
	);
}

export default {
	...cloudflareHandlers,
	fetch(request, env, ctx) {
		return flueApp.fetch(request, env, ctx);
	},
};
`;
}
