#!/usr/bin/env node
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
	type BlueprintRecord,
	type KindRootRecord,
	parseBlueprintFrontmatter,
	validateBlueprintBody,
} from '../src/lib/blueprint-index.ts';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '../../..');
const blueprintsDir = join(repoRoot, 'blueprints');
const outFile = join(here, '../src/generated/blueprints.ts');

async function main() {
	const allFiles = (await readdir(blueprintsDir))
		.filter((file) => file.endsWith('.md') && file !== 'README.md')
		.sort();

	const blueprints: BlueprintRecord[] = [];
	const kindRoots: KindRootRecord[] = [];
	const seenNames = new Map<string, string>();

	for (const file of allFiles) {
		const stem = file.slice(0, -'.md'.length);
		const dashIndex = stem.indexOf('--');
		const source = await readFile(join(blueprintsDir, file), 'utf-8');
		const frontmatter = parseBlueprintFrontmatter(source, file);
		validateBlueprintBody(source, file, frontmatter.version);

		if (dashIndex >= 0) {
			if (frontmatter.root) {
				throw new Error(
					`[blueprints] ${file}: filename uses '--' separator but frontmatter has "root": true. Kind roots use the bare filename "<kind>.md".`,
				);
			}
			const kind = stem.slice(0, dashIndex);
			const slug = stem.slice(dashIndex + 2);
			if (kind !== frontmatter.kind) {
				throw new Error(
					`[blueprints] ${file}: filename kind "${kind}" does not match frontmatter kind "${frontmatter.kind}".`,
				);
			}
			const normalizedSlug = slug.toLowerCase();
			if (seenNames.has(normalizedSlug)) {
				throw new Error(
					`[blueprints] name collision: both "${seenNames.get(normalizedSlug)}" and "${file}" resolve to "${slug}". Rename one.`,
				);
			}
			seenNames.set(normalizedSlug, file);
			for (const alias of frontmatter.aliases) {
				const normalizedAlias = alias.toLowerCase();
				if (normalizedAlias === normalizedSlug) {
					throw new Error(
						`[blueprints] ${file}: alias "${alias}" duplicates the blueprint's own slug. Remove it from "aliases".`,
					);
				}
				if (seenNames.has(normalizedAlias)) {
					throw new Error(
						`[blueprints] name collision: alias "${alias}" in ${file} is already taken by ${seenNames.get(normalizedAlias)}.`,
					);
				}
				seenNames.set(normalizedAlias, file);
			}
			blueprints.push({
				slug,
				kind,
				version: frontmatter.version,
				website: frontmatter.website,
				aliases: frontmatter.aliases,
				file,
			});
		} else {
			if (!frontmatter.root) {
				throw new Error(
					`[blueprints] ${file}: bare-named file (no '--') must declare "root": true in frontmatter.`,
				);
			}
			if (stem !== frontmatter.kind) {
				throw new Error(
					`[blueprints] ${file}: filename "${stem}" does not match frontmatter kind "${frontmatter.kind}". Kind roots must be named "<kind>.md".`,
				);
			}
			const normalizedStem = stem.toLowerCase();
			if (seenNames.has(normalizedStem)) {
				throw new Error(
					`[blueprints] name collision: "${seenNames.get(normalizedStem)}" already uses "${stem}".`,
				);
			}
			seenNames.set(normalizedStem, file);
			kindRoots.push({ kind: frontmatter.kind, version: frontmatter.version, file });
		}
	}

	const banner = `// AUTO-GENERATED by scripts/generate-blueprint-index.ts. Do not edit by hand.\n`;
	const blueprintsLiteral = blueprints
		.map(
			(blueprint) =>
				`\t{ slug: ${JSON.stringify(blueprint.slug)}, kind: ${JSON.stringify(blueprint.kind)}, version: ${blueprint.version}, website: ${JSON.stringify(blueprint.website)}, aliases: ${JSON.stringify(blueprint.aliases)} },`,
		)
		.join('\n');
	const rootsLiteral = kindRoots
		.map((root) => `\t{ kind: ${JSON.stringify(root.kind)}, version: ${root.version} },`)
		.join('\n');
	const out =
		banner +
		`export const BLUEPRINTS: readonly { readonly slug: string; readonly kind: string; readonly version: number; readonly website: string; readonly aliases: readonly string[] }[] = [\n${blueprintsLiteral}\n];\n\n` +
		`export const KIND_ROOTS: readonly { readonly kind: string; readonly version: number }[] = [\n${rootsLiteral}\n];\n`;

	await mkdir(dirname(outFile), { recursive: true });
	await writeFile(outFile, out, 'utf-8');
	console.error(
		`[blueprints] wrote ${outFile} (${blueprints.length} blueprints, ${kindRoots.length} kind roots)`,
	);
}

main().catch((err) => {
	console.error(err instanceof Error ? err.message : String(err));
	process.exit(1);
});
